{% set name = "filepattern" %}
{% set version = "2.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/PolusAI/filepattern/archive/v{{ version }}.tar.gz
  sha256: 6addc19e36219f094e625e67940b2af3b3512567ba9cfab96f2d0c9bad41c37f

build:
  skip: true  # [py2k]
  number: 0

requirements:
  build:
    - cmake
    - make  # [not win]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - git
  host:
    - python
    - setuptools
    - pip
    - pybind11
    - libfilepattern =={{ version }}
  run:
    - python
    - pydantic

test:
  imports:
    - filepattern
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/PolusAI/filepattern
  summary: Python library to store and filter files with systematic naming conventions using simplified regular expression-like patterns
  description: |
    The filepattern utility is used to store files that follow a pattern, where the pattern is analogous 
    to a simplified regular expression. The need for filepattern arises in situations where large amounts 
    of data with a systematic naming convention needs to be filtered by patterns in the naming. 
    For example, one may have a directory containing segmented images where the name contains information 
    such as the channel, the column value, and the row value. filepattern provides the ability to extract 
    all images containing such a naming pattern, filter by the row or column value, or group files by one
    or more of the aforementioned variables.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://filepattern.readthedocs.io/en/latest/
  dev_url: https://github.com/PolusAI/filepattern

extra:
  recipe-maintainers:
    - JesseMckinzie
    - sameeul
